In [1]:
import pandas as pd
import xlrd
import numpy as np
import openpyxl
import sys
from openpyxl import Workbook

In [2]:
from openpyxl import load_workbook
wb = load_workbook('Character Classification Hebbs.xlsx')

In [3]:
hebbs = wb['Hebbs']

In [4]:
#Create the table headers  for inputs, weight calculations
hebbs.cell(row = 1, column = 1).value = 'Letter'

#x1-x70 | B = 1
for i in range(1, 71):
    hebbs.cell(row = 1, column = 1 + i).value = 'x' + str(i)    
hebbs.cell(row = 1, column = 72).value = 'B = 1'

#t
hebbs.cell(row = 1, column = 73).value = 't'

#Dw1-Dw70 | Db
for i in range(1, 71):
    hebbs.cell(row = 1, column = 73 + i).value = 'Dw' + str(i)
hebbs.cell(row = 1, column = 144).value = 'Db'

#w1-w70 | b
for i in range(1, 71):
    hebbs.cell(row = 1, column = 144 + i).value = 'w' + str(i)
hebbs.cell(row = 1, column = 215).value = 'b'

In [5]:
wb.save('Character Classification Hebbs.xlsx')

In [6]:
A = pd.read_excel('CharacterSet.xlsx', sheet_name = 'A', header=None).to_numpy()
B = pd.read_excel('CharacterSet.xlsx', sheet_name = 'B', header=None).to_numpy()
C = pd.read_excel('CharacterSet.xlsx', sheet_name = 'C', header=None).to_numpy()
D = pd.read_excel('CharacterSet.xlsx', sheet_name = 'D', header=None).to_numpy()
a = pd.read_excel('CharacterSet.xlsx', sheet_name = 'a1', header=None).to_numpy()
b = pd.read_excel('CharacterSet.xlsx', sheet_name = 'b1', header=None).to_numpy()
c = pd.read_excel('CharacterSet.xlsx', sheet_name = 'c1', header=None).to_numpy()
d = pd.read_excel('CharacterSet.xlsx', sheet_name = 'd1', header=None).to_numpy()

In [7]:
data = [A, B, C, D, a, b, c, d]

In [8]:
# Converting graphical data to biploar data
for i in range(0, len(data)):
    columnNo = 2
    for row in range(0, 10):
        for col in range(0, 7):
            if data[i][row][col] == 'x':
                hebbs.cell(row = 2 + i, column = columnNo).value = 1
            else:
                hebbs.cell(row = 2 + i, column = columnNo).value = -1
            columnNo +=1
    hebbs.cell(row = 1 + i, column = 72).value = 1
wb.save("Character Classification Hebbs.xlsx")

#Enter the targets manually in t column (column number 73)
#######################################################################################################
#######################################################################################################

In [13]:
df = pd.read_excel("Character Classification Hebbs.xlsx")

In [14]:
df

,Letter,x1,x2,x3,x4,x5,x6,x7,x8,x9,...,w62,w63,w64,w65,w66,w67,w68,w69,w70,b
0,A,1,1,1,1,1,1,1,1,-1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,B,1,1,1,1,1,1,-1,1,-1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,C,-1,1,1,1,1,1,1,1,-1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,D,1,1,1,1,1,-1,-1,1,-1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,a,-1,-1,-1,-1,-1,-1,-1,-1,-1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,b,-1,-1,-1,-1,-1,-1,-1,-1,-1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,c,-1,-1,-1,-1,-1,-1,-1,-1,-1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,d,-1,-1,-1,-1,-1,-1,-1,-1,-1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [30]:
def calculate_weights(row): 
    # CALCULATE CHANGE IN WEIGHTS -> Dw(i) = xi * t
        for i in range(1, 71):
            df[str('Dw' + str(i))][row] = df[str('x' + str(i))][row] * df['t'][row] 
    #     Db = t
        df['Db'][row] =df['t'][row]

    #######################################
    # UPDATE WEIGHTS -> w(i) = w(i-1) + Dwi
        if row == 0:
            #Assuming initial weights to be 0
            for i in range(1, 71):
                df[str('w' + str(i))][row] = df[str('Dw' + str(i))][row]
            df['b'][row] = df['Db'][row] 
        else:
            for i in range(1, 71):
                df[str('w' + str(i))][row] = df[str('w'+ str(i))][row - 1] + df[str('Dw' + str(i))][row]
            df['b'][row] = df['b'][row - 1] + df['Db'][row]

In [31]:
for row in range(0, 8):
    calculate_weights(row)

C:\Users\shiva\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.
C:\Users\shiva\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

C:\Users\shiva\Anaconda3\lib\site-packages\ipykernel_launcher.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  del sys.path[0]
C:\Users\shiva\Anaconda3\lib\site-packages\ipykernel_launcher.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

C:\Users\shiva\Anaconda3\lib\site-packages\ipykernel_launcher.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\Users\shiva\Anaconda3\lib\site-packages\ipykernel_launcher.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [33]:
df.to_excel('trained_network_hebbs.xlsx')

In [ ]:
#Testing the network

In [48]:
upper = pd.read_excel('TestSet.xlsx', sheet_name = 'upper', header=None).to_numpy()
lower = pd.read_excel('TestSet.xlsx', sheet_name = 'lower', header=None).to_numpy()

In [49]:
testData = [upper, lower]

In [51]:
for letter in testData:
    result = 0
    colNo = 1
    for row in range(0, len(letter)):
        for col in range(0, len(letter[0])):
            coeff = 0
            if letter[row][col] == 'x': 
                coeff = 1
            else: 
                coeff = -1
            result += (float(df[str('w' + str(colNo))][7]) * coeff)
            colNo += 1
    print(result)

138.0
-138.0